"""reclamos tecnicos, catalogos e incidentes

Revision ID: bb679c46b4e6
Revises: 
Create Date: 2026-08-06 23:06:29.199095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pucara.db  # tipos propios (UtcDateTime)


# revision identifiers, used by Alembic.
revision: str = 'bb679c46b4e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alcance', sa.Enum('ONU', 'PON', 'OLT', 'EQUIPO_TORRE', name='alcanceincidente', native_enum=False, length=20), nullable=False),
    sa.Column('referencia', sa.String(length=120), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'RECUPERADA', 'CERRADA', name='estadoincidente', native_enum=False, length=20), nullable=False),
    sa.Column('causa_probable', sa.Enum('CORTE_ELECTRICO', 'CORTE_FIBRA', 'FALLA_OLT', 'DESCONOCIDA', name='causaprobable', native_enum=False, length=20), nullable=False),
    sa.Column('inicio', pucara.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('recuperado', pucara.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('cierre', pucara.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('usuario_cierre', sa.String(length=80), nullable=False),
    sa.Column('motivo_cierre', sa.String(length=120), nullable=True),
    sa.Column('ciclos', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=True),
    sa.Column('pon', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidentes', schema=None) as batch_op:
        batch_op.create_index('ix_incidentes_alcance', ['alcance', 'referencia'], unique=False)
        batch_op.create_index('ix_incidentes_estado', ['estado'], unique=False)
        batch_op.create_index('ix_incidentes_inicio', ['inicio'], unique=False)
        batch_op.create_index('uq_incidente_abierto', ['alcance', 'referencia'], unique=True, sqlite_where=sa.text("estado != 'CERRADA'"), postgresql_where=sa.text("estado != 'CERRADA'"))

    op.create_table('reclamo_causas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('creado', pucara.db.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_reclamo_causa_nombre')
    )
    op.create_table('reclamo_resoluciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('creado', pucara.db.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_reclamo_resolucion_nombre')
    )
    op.create_table('incidente_afectados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidente_id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=120), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('nro_cliente', sa.String(length=40), nullable=True),
    sa.Column('motivo_caida', sa.String(length=60), nullable=True),
    sa.Column('recuperado', pucara.db.UtcDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incidente_id', 'referencia', name='uq_afectado_incidente')
    )
    with op.batch_alter_table('incidente_afectados', schema=None) as batch_op:
        batch_op.create_index('ix_afectado_cliente', ['cliente_id'], unique=False)

    op.create_table('reclamos_tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_alta', pucara.db.UtcDateTime(timezone=True), nullable=False),
    sa.Column('fecha_cierre', pucara.db.UtcDateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('ABIERTO', 'EN_PROCESO', 'RESUELTO', 'CERRADO', 'ANULADO', name='estadoreclamo', native_enum=False, length=20), nullable=False),
    sa.Column('causa_id', sa.Integer(), nullable=True),
    sa.Column('resolucion_id', sa.Integer(), nullable=True),
    sa.Column('usuario_alta', sa.String(length=80), nullable=False),
    sa.Column('usuario_cierre', sa.String(length=80), nullable=True),
    sa.Column('tecnico', sa.String(length=120), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('ap_id', sa.Integer(), nullable=True),
    sa.Column('ap_nombre', sa.String(length=120), nullable=True),
    sa.Column('olt_id', sa.Integer(), nullable=True),
    sa.Column('pon', sa.Integer(), nullable=True),
    sa.Column('tipo_servicio', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['causa_id'], ['reclamo_causas.id'], ),
    sa.ForeignKeyConstraint(['resolucion_id'], ['reclamo_resoluciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reclamos_tecnicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reclamos_tecnicos_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reclamos_tecnicos_tecnico'), ['tecnico'], unique=False)
        batch_op.create_index('ix_rectec_ap', ['ap_id'], unique=False)
        batch_op.create_index('ix_rectec_causa', ['causa_id'], unique=False)
        batch_op.create_index('ix_rectec_cliente_fecha', ['cliente_id', 'fecha_alta'], unique=False)
        batch_op.create_index('ix_rectec_estado', ['estado'], unique=False)
        batch_op.create_index('ix_rectec_pon', ['olt_id', 'pon'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reclamos_tecnicos', schema=None) as batch_op:
        batch_op.drop_index('ix_rectec_pon')
        batch_op.drop_index('ix_rectec_estado')
        batch_op.drop_index('ix_rectec_cliente_fecha')
        batch_op.drop_index('ix_rectec_causa')
        batch_op.drop_index('ix_rectec_ap')
        batch_op.drop_index(batch_op.f('ix_reclamos_tecnicos_tecnico'))
        batch_op.drop_index(batch_op.f('ix_reclamos_tecnicos_cliente_id'))

    op.drop_table('reclamos_tecnicos')
    with op.batch_alter_table('incidente_afectados', schema=None) as batch_op:
        batch_op.drop_index('ix_afectado_cliente')

    op.drop_table('incidente_afectados')
    op.drop_table('reclamo_resoluciones')
    op.drop_table('reclamo_causas')
    with op.batch_alter_table('incidentes', schema=None) as batch_op:
        batch_op.drop_index('uq_incidente_abierto', sqlite_where=sa.text("estado != 'CERRADA'"), postgresql_where=sa.text("estado != 'CERRADA'"))
        batch_op.drop_index('ix_incidentes_inicio')
        batch_op.drop_index('ix_incidentes_estado')
        batch_op.drop_index('ix_incidentes_alcance')

    op.drop_table('incidentes')
    # ### end Alembic commands ###
