"""adjuntos de notas de tareas

Revision ID: d0813c9d86cb
Revises: c1a7f2d40b11
Create Date: 2026-08-07 18:14:22.385120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pucara.db  # tipos propios (UtcDateTime)


# revision identifiers, used by Alembic.
revision: str = 'd0813c9d86cb'
down_revision: Union[str, Sequence[str], None] = 'c1a7f2d40b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarea_adjuntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('propietario', sa.String(length=80), nullable=False),
    sa.Column('archivo', sa.String(length=80), nullable=False),
    sa.Column('mime', sa.String(length=40), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sa.String(length=200), nullable=True),
    sa.Column('creado', pucara.db.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('archivo')
    )
    with op.batch_alter_table('tarea_adjuntos', schema=None) as batch_op:
        batch_op.create_index('ix_adjunto_propietario', ['propietario'], unique=False)
        batch_op.create_index('ix_adjunto_tarea', ['tarea_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea_adjuntos', schema=None) as batch_op:
        batch_op.drop_index('ix_adjunto_tarea')
        batch_op.drop_index('ix_adjunto_propietario')

    op.drop_table('tarea_adjuntos')
    # ### end Alembic commands ###
