#!/usr/bin/env python3
"""Auditoría de portabilidad SQLite → PostgreSQL (preparación de las fases 7 y 8).

No modifica nada. Recorre el código y, si se le pasa, la base, y lista todo lo
que **va a romperse** al cambiar de motor. La idea es que la migración empiece
con el inventario en la mano y no descubriendo cosas en producción.

Uso:
    python3 scripts/auditoria_portabilidad.py
    python3 scripts/auditoria_portabilidad.py --db netadmin.db
    python3 scripts/auditoria_portabilidad.py --json      # para CI
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sqlite3
import sys

RAIZ = pathlib.Path(__file__).resolve().parent.parent

# Carpetas que no cuentan: histórico, dependencias, artefactos, y las pruebas
# —que a propósito construyen esquemas de SQLite para verificar que las
# herramientas de migración los sobrevivan—.
EXCLUIR = {"__pycache__", ".git", "scripts_historicos", "node_modules", "uploads",
           "backups", "migrations", "tests"}

# Las herramientas de migración NOMBRAN las construcciones de SQLite porque su
# trabajo es traducirlas. Contarlas como deuda infla el número que este mismo
# informe usa para medir el avance, así que se excluyen por nombre y no por
# carpeta: el resto de `scripts/` sí se audita.
ARCHIVOS_EXCLUIDOS = {
    "auditoria_portabilidad.py",
    "esquema_heredado_a_postgres.py",
    "migrar_a_postgres.py",
}

# (clave, patrón, gravedad, qué hacer)
# gravedad: 'rompe' = falla seguro en PostgreSQL · 'revisar' = cambia de semántica
HALLAZGOS: list[tuple[str, str, str, str]] = [
    ("date_now", r"\bdate\s*\(\s*'now'", "rompe",
     "date('now') no existe en PostgreSQL. Usar CURRENT_DATE o resolverlo en Python."),
    ("datetime_now", r"\bdatetime\s*\(\s*'now'", "rompe",
     "datetime('now') → NOW() / CURRENT_TIMESTAMP, o mejor resolverlo en Python."),
    ("strftime", r"\bstrftime\s*\(", "rompe",
     "strftime() es de SQLite. En PostgreSQL es to_char()/date_trunc()."),
    ("julianday", r"\bjulianday\s*\(", "rompe",
     "julianday() no existe. La aritmética de fechas se resuelve con intervalos."),
    ("pragma", r"\bPRAGMA\b", "rompe",
     "PRAGMA es exclusivo de SQLite (table_info → information_schema)."),
    ("autoincrement", r"\bAUTOINCREMENT\b", "rompe",
     "AUTOINCREMENT → GENERATED BY DEFAULT AS IDENTITY."),
    ("insert_or", r"\bINSERT\s+OR\s+(REPLACE|IGNORE)\b", "rompe",
     "INSERT OR REPLACE/IGNORE → INSERT ... ON CONFLICT (...) DO UPDATE/NOTHING."),
    ("ifnull", r"\bIFNULL\s*\(", "rompe",
     "IFNULL() → COALESCE()."),
    ("group_concat", r"\bGROUP_CONCAT\s*\(", "rompe",
     "GROUP_CONCAT() → STRING_AGG(col, ',')."),
    ("sqlite3_connect", r"sqlite3\.connect", "rompe",
     "Conexión directa a SQLite. Debe pasar por pucara/db.py."),
    ("placeholder", r"execute\(\s*[\"'].*\?", "rompe",
     "Marcador '?': psycopg usa '%s'. Con SQLAlchemy el problema desaparece."),
    ("like", r"\bLIKE\s+[?'%]", "revisar",
     "LIKE en SQLite ignora mayúsculas; en PostgreSQL no. Probablemente sea ILIKE."),
    ("bool_entero", r"=\s*1\b.*\bonline\b|\bonline\s*=\s*[01]\b", "revisar",
     "Booleanos guardados como 0/1: revisar al tipar la columna como BOOLEAN."),
    ("rowid", r"\browid\b", "revisar",
     "rowid no existe en PostgreSQL."),
]


def _archivos_py() -> list[pathlib.Path]:
    return [
        p for p in RAIZ.rglob("*.py")
        if not (set(p.relative_to(RAIZ).parts) & EXCLUIR)
        and p.name not in ARCHIVOS_EXCLUIDOS
    ]


def _sin_comentario(linea: str) -> str:
    """Descarta los comentarios de línea.

    Sin esto la propia documentación se cuenta como hallazgo: hay comentarios
    que dicen "julianday() no existe en PostgreSQL" justamente para explicar por
    qué NO se usa. Es un filtro simple, no un parser: alcanza para bajar el
    ruido sin arriesgar falsos negativos en el SQL real, que va entre comillas.
    """
    desnuda = linea.lstrip()
    if desnuda.startswith("#") or desnuda.startswith('"""') or desnuda.startswith("'''"):
        return ""
    corte = linea.find("#")
    # Un '#' dentro de comillas no abre comentario; si hay comillas antes, no cortar.
    if corte > 0 and not re.search(r"""["'].*#""", linea[:corte + 1]):
        return linea[:corte]
    return linea


def auditar_codigo() -> dict:
    por_clave: dict[str, dict] = {}
    for p in _archivos_py():
        try:
            lineas = p.read_text(encoding="utf-8").splitlines()
        except UnicodeDecodeError:
            continue
        rel = str(p.relative_to(RAIZ))
        for clave, patron, gravedad, arreglo in HALLAZGOS:
            rx = re.compile(patron, re.I)
            hits = [n for n, l in enumerate(lineas, 1) if rx.search(_sin_comentario(l))]
            if hits:
                d = por_clave.setdefault(
                    clave, {"gravedad": gravedad, "arreglo": arreglo, "total": 0, "archivos": {}}
                )
                d["archivos"][rel] = hits
                d["total"] += len(hits)
    return por_clave


def auditar_base(ruta: str) -> dict:
    """Revisa el esquema real: lo que el código no muestra."""
    if not pathlib.Path(ruta).exists():
        return {"error": f"No se encontró {ruta}"}
    con = sqlite3.connect(ruta)
    con.row_factory = sqlite3.Row
    tablas = [
        r["name"] for r in con.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
        )
    ]

    sin_pk, fechas_texto, sin_fk_declarada, grandes = [], [], [], []
    for t in tablas:
        cols = list(con.execute(f'PRAGMA table_info("{t}")'))
        if not any(c["pk"] for c in cols):
            sin_pk.append(t)
        # Fechas guardadas como TEXT: es LA fuente de sorpresas al migrar,
        # porque PostgreSQL sí valida el formato al tipar la columna.
        for c in cols:
            nombre = (c["name"] or "").lower()
            tipo = (c["type"] or "").upper()
            if ("fecha" in nombre or nombre.endswith("_at") or "hora" in nombre) \
                    and tipo in ("TEXT", "", "VARCHAR"):
                fechas_texto.append(f"{t}.{c['name']}")
        # Columnas *_id sin FOREIGN KEY declarada
        fks = {r["from"] for r in con.execute(f'PRAGMA foreign_key_list("{t}")')}
        for c in cols:
            n = c["name"] or ""
            if n.endswith("_id") and n not in fks and not c["pk"]:
                sin_fk_declarada.append(f"{t}.{n}")
        try:
            n = con.execute(f'SELECT COUNT(*) FROM "{t}"').fetchone()[0]
            if n > 100_000:
                grandes.append(f"{t} ({n:,} filas)")
        except sqlite3.Error:
            pass

    # Valores de fecha que PostgreSQL rechazaría
    fechas_invalidas = []
    rx_fecha = re.compile(r"^\d{4}-\d{2}-\d{2}")
    for ref in fechas_texto:
        t, c = ref.split(".", 1)
        try:
            malos = con.execute(
                f'SELECT COUNT(*) FROM "{t}" WHERE "{c}" IS NOT NULL AND TRIM("{c}") != ""'
            ).fetchone()[0]
            if not malos:
                continue
            muestra = [
                r[0] for r in con.execute(
                    f'SELECT DISTINCT "{c}" FROM "{t}" '
                    f'WHERE "{c}" IS NOT NULL AND TRIM("{c}") != "" LIMIT 200'
                )
            ]
            raros = [v for v in muestra if not rx_fecha.match(str(v))]
            if raros:
                fechas_invalidas.append({"columna": ref, "ejemplos": raros[:5]})
        except sqlite3.Error:
            pass

    con.close()
    return {
        "tablas": len(tablas),
        "sin_clave_primaria": sin_pk,
        "fechas_como_texto": fechas_texto,
        "fechas_con_formato_invalido": fechas_invalidas,
        "columnas_id_sin_foreign_key": sin_fk_declarada,
        "tablas_grandes": grandes,
    }


def _imprimir(codigo: dict, base: dict | None) -> int:
    rompe = {k: v for k, v in codigo.items() if v["gravedad"] == "rompe"}
    revisar = {k: v for k, v in codigo.items() if v["gravedad"] == "revisar"}

    print("═" * 72)
    print("  AUDITORÍA DE PORTABILIDAD SQLite → PostgreSQL")
    print("═" * 72)

    for titulo, grupo in (("ROMPE EN POSTGRESQL", rompe), ("REVISAR (cambia la semántica)", revisar)):
        print(f"\n▓ {titulo}\n")
        if not grupo:
            print("   (nada)")
            continue
        for clave, d in sorted(grupo.items(), key=lambda kv: -kv[1]["total"]):
            print(f"  ● {clave}  — {d['total']} apariciones en {len(d['archivos'])} archivos")
            print(f"      {d['arreglo']}")
            for arch, lineas in sorted(d["archivos"].items(), key=lambda kv: -len(kv[1]))[:6]:
                muestra = ", ".join(str(x) for x in lineas[:6])
                mas = f" (+{len(lineas)-6})" if len(lineas) > 6 else ""
                print(f"        {arch}: líneas {muestra}{mas}")
            if len(d["archivos"]) > 6:
                print(f"        … y {len(d['archivos'])-6} archivos más")

    if base is not None:
        print("\n▓ ESQUEMA DE LA BASE\n")
        if "error" in base:
            print(f"   {base['error']}")
        else:
            print(f"  Tablas: {base['tablas']}")
            for etiqueta, clave in (
                ("Sin clave primaria", "sin_clave_primaria"),
                ("Columnas *_id sin FOREIGN KEY", "columnas_id_sin_foreign_key"),
                ("Fechas guardadas como texto", "fechas_como_texto"),
                ("Tablas grandes (planificar la copia)", "tablas_grandes"),
            ):
                items = base[clave]
                print(f"  {etiqueta}: {len(items)}")
                for x in items[:10]:
                    print(f"      · {x}")
                if len(items) > 10:
                    print(f"      … y {len(items)-10} más")
            inv = base["fechas_con_formato_invalido"]
            print(f"  Fechas con formato que PostgreSQL rechazaría: {len(inv)}")
            for x in inv[:10]:
                print(f"      · {x['columna']}: {x['ejemplos']}")

    total_rompe = sum(d["total"] for d in rompe.values())
    print("\n" + "═" * 72)
    print(f"  {total_rompe} usos que hay que reescribir antes de migrar.")
    print("═" * 72)
    return 1 if total_rompe else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", help="Ruta a la base SQLite a inspeccionar")
    ap.add_argument("--json", action="store_true", help="Salida JSON")
    a = ap.parse_args()

    codigo = auditar_codigo()
    base = auditar_base(a.db) if a.db else None

    if a.json:
        print(json.dumps({"codigo": codigo, "base": base}, indent=2, ensure_ascii=False))
        return 0
    return _imprimir(codigo, base)


if __name__ == "__main__":
    sys.exit(main())
